changelog:
  exclude:
    labels:
      - skip-changelog
      - dependencies
      - chore
  categories:
    - title: Breaking Changes
      labels:
        - breaking-change
    - title: Features
      labels:
        - feat
        - feature
        - enhancement
    - title: Fixes
      labels:
        - fix
        - bug
        - bugfix
    - title: Documentation
      labels:
        - docs
    - title: Maintenance
      labels:
        - refactor
        - test
        - ci
        - build
